name: Check Pull Request

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    env:
      ENV_TYPE: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if hotfix branch
        if: startsWith(github.head_ref, 'hotfix/')
        run: |
          echo -e "\e[31mURGENCE DETECTÉE\e[0m"
          echo "Type d'environnement : ${{ env.ENV_TYPE }}"

      - name: Display Env Variable
        if: "!startsWith(github.head_ref, 'hotfix/')"
        run: echo "Environnement standard : ${{ env.ENV_TYPE }}"
